defaults:
  - reducer: PCA
  - dataset: SwissRoll
  - optional dataset_reducer: ${dataset}_${reducer}
  - _self_

n_jobs: 1

# this can be set to True in the dataset_reducer config group for a specific combination
_skip_: False

available_datasets:
  - MNIST
  - CIFAR10
  - SwissRoll

reducer:
  callbacks:
    - _target_: skorch.callbacks.ProgressBar

use_pretrained: False

root_dir: .
data_dir: data
log_dir: logs
model_dir: models
