defaults:
  - _self_
  - reducer: PCA
  - dataset: SwissRoll
  - optional dataset_reducer: ${dataset}_${reducer}

# Because the evaluation of the models is expensive, there is support to disable it.
evaluate: False

# this can be set to True in the dataset_reducer config group for a specific combination
_skip_: False

wandb:
  project: drcomp

available_datasets:
  - MNIST
  - CIFAR10
  - SwissRoll
  - LfwPeople
  - OlivettiFaces
  - TwinPeaks
  - FER2013
  - 20News
  - ICMR
  - FashionMNIST

available_reducers:
  - PCA
  - kPCA
  - LLE
  - AE
  - ConvAE
  - CAE

# some defaults for all reducers
reducer:
  _max_sample_size_: null # by default, use all samples
  intrinsic_dim: ${dataset.intrinsic_dim} # no need to specify this for each reducer
  n_jobs: 1 # by default no parallelization
  callbacks:
    - _target_: skorch.callbacks.ProgressBar
    - _target_: skorch.callbacks.LRScheduler
      policy: ExponentialLR
      monitor: valid_loss
      gamma: 0.9
    - _target_: skorch.callbacks.EarlyStopping
      monitor: valid_loss
      load_best: True
      patience: 20

preprocessor:
  _target_: sklearn.preprocessing.StandardScaler

use_gpu: True
use_pretrained: False
max_n_neighbors: 100
max_evaluation_samples: 5000 # == maximum coranking dimension

root_dir: .
# the following directories are relative to root_dir
data_dir: data
log_dir: logs
model_dir: models
metrics_dir: metrics
figures_dir: figures
