defaults:
  - reducer: PCA
  - dataset: SwissRoll
  - optional dataset_reducer: ${dataset}_${reducer}
  - _self_

# Because the evaluation of the models is expensive, there is support to disable it.
evaluate: False

# this can be set to True in the dataset_reducer config group for a specific combination
_skip_: False

available_datasets:
  - MNIST
  - CIFAR10
  - SwissRoll
  - LfwPeople

reducer:
  intrinsic_dim: ${dataset.intrinsic_dim} # no need to specify this for each reducer
  callbacks:
    - _target_: skorch.callbacks.ProgressBar

use_pretrained: False

root_dir: .
# the following directories are relative to root_dir
data_dir: data
log_dir: logs
model_dir: models
metrics_dir: metrics
