_target_: drcomp.reducers.AutoEncoder
_name_: CAE
_flatten_: True
contractive: True
contractive_lambda: 0.0001
AutoEncoderClass:
  _target_: drcomp.autoencoder.FullyConnectedAE
  input_size: ${dataset.flattened_size}
  intrinsic_dim: ${dataset.intrinsic_dim}
  hidden_layer_dims: []
  encoder_act_fn:
    _target_: torch.nn.Sigmoid
    _partial_: True
  decoder_act_fn:
    _target_: torch.nn.Sigmoid
    _partial_: True
  include_batch_norm: False
  tied_weights: False
criterion:
  _target_: torch.nn.MSELoss
  _partial_: True
lr: 0.1
weight_decay: 0.0
max_epochs: 20
callbacks:
  - _target_: skorch.callbacks.ProgressBar
  - _target_: skorch.callbacks.LRScheduler
    policy: ExponentialLR
    monitor: valid_loss
    gamma: 0.9
  - _target_: skorch.callbacks.EarlyStopping
    monitor: valid_loss
    load_best: True
    patience: 5
