_target_: drcomp.reducers.AutoEncoder
_name_: CAE
_flatten_: True
contractive: True
contractive_lambda: 0.001
AutoEncoderClass:
  _target_: drcomp.autoencoder.FullyConnectedAE
  input_size: ${dataset.flattened_size}
  intrinsic_dim: ${dataset.intrinsic_dim}
  hidden_layer_dims: []
  act_fn:
    _target_: torch.nn.Sigmoid
    _partial_: True
  include_batch_norm: False
  tied_weights: False
criterion:
  _target_: torch.nn.MSELoss
  _partial_: True
lr: 0.1
weight_decay: 0.01
max_epochs: 20
