_target_: drcomp.reducers.AutoEncoder
_name_: ConvAE
_flatten_: False
AutoEncoderClass:
  _target_: drcomp.autoencoder.MnistConvAE
  intrinsic_dim: ${dataset.intrinsic_dim}
criterion:
  _target_: torch.nn.MSELoss
  _partial_: True
lr: 0.1
weight_decay: 0.0
max_epochs: 150
callbacks:
  - _target_: skorch.callbacks.ProgressBar
  - _target_: skorch.callbacks.LRScheduler
    policy: ExponentialLR
    monitor: valid_loss
    gamma: 0.9
  - _target_: skorch.callbacks.EarlyStopping
    monitor: valid_loss
    load_best: True
    patience: 10
