_target_: drcomp.reducers.AutoEncoder
_name_: ConvAE
_flatten_: False
AutoEncoderClass:
  _target_: drcomp.autoencoder.MnistConvAE
  intrinsic_dim: ${dataset.intrinsic_dim}
criterion:
  _target_: torch.nn.MSELoss
  _partial_: True
lr: 0.1
optimizer__weight_decay: 0.01
max_epochs: 150
