_target_: drcomp.reducers.KernelPCA
_name_: KernelPCA
_flatten_: True
_max_sample_size_: 15000
kernel: rbf
fit_inverse_transform: False
gamma: null
degree: 3
coef0: 1
kernel_params: null
alpha: 1.0
eigen_solver: auto
tol: 0
max_iter: null
iterated_power: auto
remove_zero_eig: False
random_state: null
copy_X: True
