_target_: drcomp.reducers.LLE
_name_: LLE
_flatten_: True
_max_sample_size_: 20000
n_neighbors: 10
reg: 1e-3
eigen_solver: auto
tol: 1e-6
max_iter: 100
hessian_tol: 1e-4
modified_tol: 1e-12
neighbors_algorithm: auto
random_state: null
