_target_: drcomp.reducers.MDS
_name_: MDS
_flatten_: True
metric: True
n_init: 4
max_iter: 300
eps: 0.0001
verbose: 0
random_state: null # we have to use null instead of None here
dissimilarity: euclidean
normalized_stress: False
