_target_: drcomp.reducers.AutoEncoder
_name_: MNIST_AE
_flatten_: True
AutoEncoderClass:
  _target_: drcomp.autoencoder.FullyConnectedAE
  input_size: 784
  intrinsic_dim: 16
  hidden_layer_dims: [256]
  act_fn:
    _target_: torch.nn.Sigmoid
    _partial_: True
  include_batch_norm: False
criterion:
  _target_: torch.nn.MSELoss
  _partial_: True
