name: LfwPeople
image_size:
  - 1
  - 62
  - 47
flattened_size: 2914
intrinsic_dim: 22
batch_size: 16
n_samples: 1288 # this depends on arguments here, like min_faces_per_person
resize: 0.5
min_faces_per_person: 0
color: False
