name: LfwPeople
image_size:
  - 1
  - 62
  - 47
flattened_size: 2914
intrinsic_dim: ???
batch_size: 16
resize: 0.5
n_samples: ??? # depends on min_faces_per_person
min_faces_per_person: 10
color: False
