name: LfwPeople
image_size:
  - 1
  - 62
  - 47
flattened_size: 2914
intrinsic_dim: 21
batch_size: 64
resize: 0.5
n_samples: 2370 # depends on min_faces_per_person
min_faces_per_person: 30
color: False
