name: LfwPeople
image_size:
  - width: 62
  - height: 47
  - channels: 1
flattened_size: 2914
intrinsic_dim: 22
batch_size: 16
n_samples: 1288 # this depends on arguments here, like min_faces_per_person
funneled: True
resize: 0.5
min_faces_per_person: 0
color: False
return_X_y: False
